name: Build

on:
  # Run the build for pushes and pull requests targeting main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout and setup
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install and build
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      # Deploy, limited to the main branch
      - name: Deploy
        if: success() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/.vuepress/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: cashudevkit.org
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      # Run linkcheck, propagate linkcheck failure through grep pipe
      - name: Linkcheck
        run: set -o pipefail; npm run linkcheck 2>/dev/null | grep "Getting links from\|BROKEN"
        continue-on-error: true
